<?php
$title = array();
$excelLink = $this->excelLink;

$title['title'] = $this->title;

$allMonthInYearText = $this->allMonthInYearText;
$config = \Velacolib\Utility\Utility::getConfig();
$this->titleHelper($title);
$allUser = \Velacolib\Utility\Utility::getUser();
$allMenu = \Velacolib\Utility\Utility::getCategories();
$translate = \Velacolib\Utility\Utility::translate();

?>
<div class="row-fluid">
    <div class="span12 box bordered-box blue-border ">
        <div class="box-header red-background">
            <div class="title">
                <?php echo $translate->translate('Report'); ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="row-fluid">
            <div class="box-content">
                <form method="post" action="<?php echo $this->url('admin/child',array('controller'=>'report')) ?>">
                    <div class="row-fluid">
                        <strong><?php echo $translate->translate('From Date'); ?></strong>
                        <div>
                            <div class="datepicker input-append" id="datepicker">
                                <input name="formDate" class="input-medium" data-format="yyyy-MM-dd" placeholder="" type="text" value="<?php echo $this->fromDate; ?>">
                <span class="add-on">
                  <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar"></i>
                </span>
                            </div>
                        </div>
                    </div>
                    <hr class="hr-normal">

                    <div class="row-fluid">
                        <strong><?php echo $translate->translate('To Date'); ?></strong>
                        <div>
                            <div class="datepicker input-append" id="datepicker">
                                <input class="input-medium" name="toDate" data-format="yyyy-MM-dd" placeholder="" type="text" value="<?php echo $this->toDate ?>">
                <span class="add-on">
                  <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar"></i>
                </span>
                            </div>
                        </div>
                    </div>
                    <hr class="hr-normal">

                    <div class="row-fluid">
                        <strong><?php echo $translate->translate('User'); ?></strong>
                        <div>
                            <select name="user">
                                <option value="0"><?php echo $translate->translate('Please Select User'); ?></option>
                                <?php if(!empty($allUser)){
                                    foreach($allUser as $user){  ?>
                                        <option value="<?php echo $user->getId(); ?>"><?php echo $user->getUserName(); ?></option>
                                    <?php    }
                                } ?>
                            </select>
                        </div>
                    </div>
                    <hr class="hr-normal">

                    <div class="row-fluid">
                        <strong><?php echo $translate->translate('Menu'); ?></strong>
                        <div>
                            <select name="menu">
                                <option value="0"><?php echo $translate->translate('Please Select Menu'); ?></option>
                                <?php if(!empty($allMenu)){
                                    foreach($allMenu as $menu){  ?>
                                        <option value="<?php echo $menu->getId(); ?>"><?php echo $menu->getName(); ?></option>
                                    <?php    }
                                } ?>
                            </select>
                        </div>
                    </div>

                    <hr class="hr-normal">
                    <div class="row-fluid">
                        <button class="btn btn-info" name="button" type="submit"><?php echo $translate->translate('Report'); ?></button>
                    </div>
                    <div class="row-fluid" style="margin-top: 10px">

                        <?php
                        echo  '<a class="btn btn-success" href="/'.$excelLink.'">Download excel report</a>';
                        ?>
                    </div>
                </form>
            </div>
        </div>
        <?php if(isset($this->reportText)){ ?>
            <div class="row-fluid" >
                <div class="span12 ">
                    <div class="box-content box-statistic">
                    <h4 class="text-grass-green"><?php echo $this->reportText; ?></h4>
                    </div>
                </div>
            </div>
      <?php   } ?>

        <div class="row-fluid" style="margin-top: 6px">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-error"><?php echo number_format($this->totalTable); ?></h3>
                    <small><?php echo $translate->translate('You have total'); ?></small>
                    <div class="text-error icon-inbox align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-warning"><?php echo \Velacolib\Utility\Utility::formatCost($this->tCost); ?></h3>
                    <small><?php echo $translate->translate('Total Cost'); ?></small>
                    <div class="text-warning icon-money align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-info"><?php echo \Velacolib\Utility\Utility::formatCost($this->tRCost) ; ?></h3>
                    <small><?php echo $translate->translate('Total Real Cost'); ?></small>
                    <div class="text-info icon-money align-right"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if(isset($this->reportMenu)) : ?>
<div class="row-fluid">
    <!-- table box -->
    <div class="span12 box">
        <div class="box-header">
            <div class="title">
                <?php echo $translate->translate('MENU') ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($reportMenu);
            ?>
        </div>
    </div>
    <!--end table box -->

</div>
    <script type="text/javascript">
        $(document).ready(function(){

            $('.dataTable').dataTable({
                "bProcessing": false,
                "bServerSide": false
            }) ;

        })  ;
    </script>
<?php endif ?>
