<?php
$excelLink = $this->excelLink;
$data = $this->data_table;
$dataUser = $this->data_user;
$dataMenu = $this->data_menu;
$dataMenuCostType = $this->data_menu_costtype;
$title = $this->title;
$dateTimeReport = $this->datetimeReport;
$fromDateText = $this->fromDateText;
$toDateText = $this->toDateText;
$submitText = $this->submitText;
$reportMonth = $this->reportMonth;
$allMonthInYearText = $this->allMonthInYearText;
$config = \Velacolib\Utility\Utility::getConfig();
$title = array();
$title['title'] = $this->title;
$title['link'] =   $this->url('admin/child', array('controller'=>'surtax','action' => 'add'));
$this->titleHelper($title);
$allUser = \Velacolib\Utility\Utility::getUser();
$allMenu = \Velacolib\Utility\Utility::getCategories();
?>
<div class="row-fluid">
    <div class="row-fluid">
        <div class="span12 box">
            <div class="box-header">
                <div class="title">
                    <i class="icon-check"></i>
                    Select Year
                </div>
                <div class="actions">
                    <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                    </a>
                    <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                    </a>
                </div>
            </div>
            <div class="box-content">
                <form action="/admin/report" method="get">
                    <select name="year">
                        <?php
                            for($i = 2013; $i <= $config['end_year']; $i++){
                               echo '<option value="'.$i.'">'.$i.'</option>';
                            }
                        ?>
                    </select>

                    <hr class="hr-normal">
                    <input type="submit" class="btn btn-info" value="year">
                </form>
            </div>
        </div>

    </div>
</div>
<!--control box -->
<div class="row-fluid">
    <div class="span4 box bordered-box blue-border ">
        <div class="box-header red-background">
            <div class="title">
               <?php echo $dateTimeReport; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="row-fluid">
        <div class="box-content">
            <form method="post" action="<?php echo $this->url('admin/child',array('controller'=>'report')) ?>">
                <div class="row-fluid">
                    <strong><?php echo $fromDateText ?></strong>
                    <div>
                        <div class="datepicker input-append" id="datepicker">
                            <input name="formDate" class="input-medium" data-format="yyyy-MM-dd" placeholder="<?php echo $fromDateText ?>" type="text" value="<?php echo $this->fromDate; ?>">
                <span class="add-on">
                  <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar"></i>
                </span>
                        </div>
                    </div>
                </div>
                <hr class="hr-normal">

                <div class="row-fluid">
                    <strong><?php echo $toDateText ?></strong>
                    <div>
                        <div class="datepicker input-append" id="datepicker">
                            <input class="input-medium" name="toDate" data-format="yyyy-MM-dd" placeholder="<?php echo $toDateText ?>" type="text" value="<?php echo $this->toDate ?>">
                <span class="add-on">
                  <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar"></i>
                </span>
                        </div>
                    </div>
                </div>
                <hr class="hr-normal">

                <div class="row-fluid">
                    <strong>User</strong>
                    <div>
                        <select name="user">
                            <option value="0">Please select user</option>
                            <?php if(!empty($allUser)){
                                foreach($allUser as $user){  ?>
                                    <option value="<?php echo $user->getId(); ?>"><?php echo $user->getUserName(); ?></option>
                                <?php    }
                            } ?>
                        </select>
                    </div>
                </div>
                <hr class="hr-normal">

                <div class="row-fluid">
                    <strong>Menu</strong>
                    <div>
                        <select name="menu">
                            <option value="0">Please select Category Menu</option>
                            <?php if(!empty($allMenu)){
                                foreach($allMenu as $menu){  ?>
                                    <option value="<?php echo $menu->getId(); ?>"><?php echo $menu->getName(); ?></option>
                                <?php    }
                            } ?>
                        </select>
                    </div>
                </div>

                <hr class="hr-normal">
                <div class="row-fluid">
                    <button class="btn btn-info" name="button" type="submit"><?php echo $submitText ?></button>
                    </div>
                <div class="row-fluid" style="margin-top: 10px">

                    <?php
                        echo  '<a class="btn btn-success" href="/'.$excelLink.'">Download excel report</a>';
                    ?>
                </div>
            </form>
        </div>
        </div>
        <div class="row-fluid" style="margin-top: 6px">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-error"><?php echo number_format($this->allOrder[0]['count_table']); ?></h3>
                    <small><?php echo $this->allOrderText; ?></small>
                    <div class="text-error icon-inbox align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-warning"><?php echo number_format($this->allOrder[0]['tCost']); ?></h3>
                    <small><?php echo $this->allOrderTotalCostText; ?></small>
                    <div class="text-warning icon-money align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-info"><?php echo number_format($this->allOrder[0]['tRCost']); ?></h3>
                    <small><?php echo $this->allOrderTotalRealCostText; ?></small>
                    <div class="text-info icon-money align-right"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- bar chart count order -->
    <div class="span8 box bordered-box blue-border ">
        <div class='box-header'>
            <div class='title'>
                <?php echo $allMonthInYearText; ?>
            </div>
            <div class='actions'>
                <a href="#" class="btn box-remove btn-mini btn-link"><i class='icon-remove'></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class='box-content'>
            <div id="columnchart_material_1" style="width: 100%; height: 500px;"></div>
            <?php
            //            echo '<pre>';
            //          print_r($reportMonth);
            //          echo '</pre>';
            ?>
        </div>
    </div>
    <!--end bar count order  -->
</div>
<!-- bar chart cost -->
<div class="row-fluid">
    <div class="span12 box bordered-box blue-border ">
        <div class='box-header'>
            <div class='title'>
                <?php echo $allMonthInYearText; ?>
            </div>
            <div class='actions'>
                <a href="#" class="btn box-remove btn-mini btn-link"><i class='icon-remove'></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class='box-content'>
            <div id="columnchart_material" style="width: 100%; height: 500px;"></div>
            <?php
            //            echo '<pre>';
            //          print_r($reportMonth);
            //          echo '</pre>';
            ?>
        </div>
    </div>
    <!--end bar chart cost -->
</div>
<!--end control box -->
<div class="row-fluid">
    <!-- table box -->
    <div class="span6 box">
        <div class="box-header">
            <div class="title">
                <?php echo $this->report_table_box; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($data);
            ?>
        </div>
    </div>
    <!--end table box -->
        <!-- user -->
    <div class="span6 box">
        <div class="box-header">
            <div class="title">
                <?php echo $this->report_user_box; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($dataUser);
            ?>
        </div>
    </div>
</div>
<div class="row-fluid">
    <!--Cost type -->
    <div class="span12 box">
        <div class="box-header">
            <div class="title">
                <?php echo $this->report_menu_box; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($dataMenuCostType);
            ?>
        </div>
    </div>
    <!--end cost type-->
</div>
<div class="row-fluid">
    <!-- menu box -->
    <div class="span12 box">
        <div class="box-header">
            <div class="title">
                <?php echo $this->report_menu_box; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($dataMenu);
            ?>
        </div>
    </div>
    <!--end table box -->


</div>

<div class="row-fluid">
    <!-- menu box -->
    <div class="span12 box">
        <div class="box-header">
            <div class="title">
                <?php echo $this->payment_menu_box; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <?php
            $this->tableHelper($this->data_payment);
            ?>
        </div>
    </div>
    <!--end table box -->


</div>
<!---render chart -->
<script type="text/javascript">
    $(document).ready(function(){

       $('.dataTable').dataTable({
           "bProcessing": false,
           "bServerSide": false
       }) ;

    })  ;
    google.load("visualization", "1.1", {packages:["bar"]});
    google.setOnLoadCallback(drawChart);
    google.setOnLoadCallback(drawChart1);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Month', 'Total cost', 'Total real cost'],
            <?php
                for($i =1; $i<=12; $i++)
                {

                $totalCost = isset($reportMonth[$i]['totalCost'])?$reportMonth[$i]['totalCost']:0;
                $totalRealCost = isset($reportMonth[$i]['totalCost'])?$reportMonth[$i]['totalRealCost']:0;
//                $countOrder = isset($reportMonth[$i]['countOrder'])?$reportMonth[$i]['countOrder']:0;
                 //$data[] = array($totalCost, $totalRealCost, $countOrder);

                    echo '[\''.$i.'\',  '.$totalCost.','.$totalRealCost.'],';
                }
                 // echo json_encode($data);
            ?>
        ]);
        var options = {
            chart: {
                title: '',
                subtitle: ''
            }
        };
        var chart = new google.charts.Bar(document.getElementById('columnchart_material'));
        chart.draw(data, options);
    }
    function drawChart1() {
        var data = google.visualization.arrayToDataTable([
            ['Month', 'Count order'],
            <?php
                for($i =1; $i<=12; $i++)
                {

//                $totalCost = isset($reportMonth[$i]['totalCost'])?$reportMonth[$i]['totalCost']:0;
//                $totalRealCost = isset($reportMonth[$i]['totalCost'])?$reportMonth[$i]['totalRealCost']:0;
                $countOrder = isset($reportMonth[$i]['countOrder'])?$reportMonth[$i]['countOrder']:0;
                 //$data[] = array($totalCost, $totalRealCost, $countOrder);

                    echo '[\''.$i.'\',  '.$countOrder.'],';
                }
                 // echo json_encode($data);
            ?>
        ]);
        var options = {
            chart: {
                title: '',
                subtitle: ''
            }
        };
        var chart = new google.charts.Bar(document.getElementById('columnchart_material_1'));
        chart.draw(data, options);
    }
</script>
<!--end render chart -->

