<?php
$reports = $this->report;
$end = $this->end;
$start = $this->start;
$totalQuantity = $this->totalQuantity;
$totalCost = $this->totalCost;
$linkDownload = $this->linkDownload;
$title = $this->title;
$translator = Velacolib\Utility\Utility::translate();
?>
<div class='controls'>
    <div class='caret'></div>
    <div class='form-wrapper'>
        <h1 class='text-center'><?php echo $translator->translate('Report Menu By Category'); ?></h1>
        <form accept-charset="UTF-8" action="<?php echo $this->url('admin/child',array('controller'=>'report','action'=>'reportcategories')); ?>" method="post" /><div style="margin:0;padding:0;display:inline"></div>
        <div class='row-fluid'>
            <div class='span12 icon-over-input'>
                <label><?php echo $translator->translate('Start date'); ?></label>
                <div>
                    <input type="text" name="start" class="date-picker">
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <!-- -->
            <div class='span5 icon-over-input'>
                <label><?php echo $translator->translate('End date'); ?></label>
                <div>
                    <input type="text" name="end" class="date-picker">
                </div>
            </div>
            <div class="span7">
                <label><?php echo $translator->translate('Export') ?></label>
                <input type="checkbox" name="excel" value="true">
            </div>
            <!-- -->
        </div>


        <button class="btn btn-danger"  type="submit" ><?php echo $translator->translate('Find'); ?></button>
        </form>
        <div class='text-center'>
            <hr class='hr-normal' />

        </div>
    </div>
</div>
<?php if(isset($reports)): ?>
    <div class="row-fluid">
        <h3><?php echo $title; ?></h3>
        <?php if($linkDownload){ ?>
            <a href="<?php echo $linkDownload; ?>"><?php echo $translator->translate('Download excel link'); ?></a>
        <?php } ?>
        <table class="table">
            <thead>
                <th><?php echo $translator->translate('Category id'); ?></th>
                <th><?php echo $translator->translate('Category name'); ?></th>
                <th><?php echo $translator->translate('Quantity'); ?></th>
                <th><?php echo $translator->translate('Cost'); ?></th>
            </thead>
            <tbody>

            <?php
            $totals  = 0;
            foreach($reports as $report): ?>
                <tr>
                    <td><?php echo $report['category_id'] ?></td>
                    <td><?php echo $report['category_name'] ?></td>
                    <td><?php echo $report['Quantity'] ?></td>
                    <td><?php echo number_format($report['cost']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="2"><?php echo $translator->translate('Summary'); ?></td>
                <td ><?php echo $totalQuantity; ?></td>
                <td ><?php echo number_format($totalCost); ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
<?php endif ?>

