<?php ?>
<!DOCTYPE html>
<html lang="vi-VN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title>Install</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'/>

    <!--[if lt IE 9]>
    <script src='js/backend/html5shiv.js' type='text/javascript'></script>
    <![endif]-->
    <!-- hepler style here -->
    <?php $this->styleHelper(); ?>
    <!--end helper style -->
    <!--- script helper -->
    <?php $this->scriptHelper(); ?>
    <!-- end script helper -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

</head>
<body class='contrast-red sign-in contrast-background' style="padding-top: 0px !important;">
<div id='wrapper'>
    <div class="controls" style="background: none">
        <div class="caret"></div>
        <div class="form-wrapper">
        <?php echo $this->content; ?>
    </div>
    </div>
</div>



</body>
</html>