<?php
$title = array();
$excelLink = $this->excelLink;
$data = $this->data_table;
$dataUser = $this->data_user;
$dataMenu = $this->data_menu;
$dataMenuCostType = $this->data_menu_costtype;
$title['title'] = $this->title;
$dateTimeReport = $this->datetimeReport;
$fromDateText = $this->fromDateText;
$toDateText = $this->toDateText;
$submitText = $this->submitText;
$reportMonth = $this->reportMonth;
$allMonthInYearText = $this->allMonthInYearText;
$config = \Velacolib\Utility\Utility::getConfig();
$this->titleHelper($title);
$allUser = \Velacolib\Utility\Utility::getUser();
$allMenu = \Velacolib\Utility\Utility::getCategories();
?>
<div class="row-fluid">
    <div class="span12 box bordered-box blue-border">
        <div class="box-content box-statistic">
            <?php  $this->lineChartHelper($reportPerDay,'Report Income 30 nearly 30 days'); ?>
        </div>
    </div>
</div>
<!--control box -->
<div class="row-fluid">
    <div class="span6 box bordered-box blue-border ">
        <div class="box-header red-background">
            <div class="title">
                <?php echo $dateTimeReport; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="row-fluid" style="margin-top: 6px">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-error"><?php echo number_format($this->allOrder[0]['count_table']); ?></h3>
                    <small><?php echo $this->allOrderText; ?></small>
                    <div class="text-error icon-inbox align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-warning"><?php echo number_format($this->allOrder[0]['tCost']); ?></h3>
                    <small><?php echo $this->allOrderTotalCostText; ?></small>
                    <div class="text-warning icon-money align-right"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="box-content box-statistic">
                    <h3 class="title text-info"><?php echo number_format($this->allOrder[0]['tRCost']); ?></h3>
                    <small><?php echo $this->allOrderTotalRealCostText; ?></small>
                    <div class="text-info icon-money align-right"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- bar chart count order -->
    <div class="span6 box bordered-box blue-border ">
        <div class='box-content'>
            <?php  $this->pieChartHelper($dataUser,'Report user'); ?>
        </div>
    </div>
    <!--end bar count order  -->
</div>
<!-- bar chart cost -->
<!--end control box -->
<div class="row-fluid">
    <!-- table box -->
    <div class="span6 box">
        <div class="box-content">
            <?php
            $this->tableHelper($data);
            ?>
        </div>
    </div>
    <!--end table box -->
    <!-- user -->
    <div class="span6 box">
        <div class="box-content">
            <?php
            $this->tableHelper($dataMenu);
            ?>
        </div>
    </div>
</div>
<div class="row-fluid">
    <!--Cost type -->
    <div class="span12 box">
        <div class="box-content">
            <?php
            $this->tableHelper($dataMenuCostType);
            ?>
        </div>
    </div>
    <!--end cost type-->
</div>
<div class="row-fluid">
    <!-- menu box -->
    <div class="span12 box">
        <div class="box-content">
            <?php
            $this->tableHelper($dataMenu);
            ?>
        </div>
    </div>
    <!--end table box -->


</div>
<div class="row-fluid">
    <!-- menu box -->
    <div class="span12 box">

        <div class="box-content">
            <?php
            $this->tableHelper($this->data_payment);
            ?>
        </div>
    </div>
    <!--end table box -->


</div>


