<?php
$translator = \Velacolib\Utility\Utility::translate();
$config = Velacolib\Utility\Utility::getConfig();

?>
<!DOCTYPE html>
<html  lang="vi-VN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $config['sitename'] ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'/>
    <meta name="description" content="<?php echo $config['meta_description'] ?>">
    <!--[if lt IE 9]>
    <script src='js/backend/html5shiv.js' type='text/javascript'></script>
    <![endif]-->
    <!-- hepler style here -->
    <?php $this->styleHelper(); ?>
    <!--end helper style -->
    <!--- script helper -->
    <?php $this->scriptHelper(); ?>
    <!-- end script helper -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body class='contrast-red '>
<div class="loading">Loading&#8230;</div>
<!-- header -->
<?php $this->headerHelper(); ?>
<!-- end header -->
<!--menu here -->
<?php $this->leftMenuHelper(); ?>
<!--end menu -->
</div>
</nav>
<section id='content'>
<div class='container-fluid'>
<div class='row-fluid' id='content-wrapper'>
<div class='span12'>
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->content; ?>
        </div>
    </div>

</div>
</div>
</div>
</section>
</div>

</body>
</html>