<?php

    $contentDiv = isset($this->contentDiv)?$this->contentDiv:'piechart';
    $title = isset($this->title)?$this->title:'My Daily Activities';
    $jsonData = $this->data;
   // $data = json_encode(array($data));
    $jsonData = str_replace(":",",",json_encode($jsonData));
    $jsonData = str_replace("{","[",$jsonData);
    $jsonData = str_replace("}","]",$jsonData);
?>
<div id="<?php echo $contentDiv; ?>" style="width: 100%; height: 300px;"></div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
          var data = google.visualization.arrayToDataTable(<?php echo $jsonData; ?>);
          var options = {
              title: '<?php echo $title ?>'
        };
        var chart = new google.visualization.PieChart(document.getElementById('<?php echo $contentDiv ?>'));
        chart.draw(data, options);
      }
    </script>