<?php
$title = array();
$dataOrder = $this->data;
$dataRow = $dataOrder['data'];
$heading = $dataOrder['heading'];
$link = $dataOrder['link'];
$title['title'] = $dataOrder['title'];
$button = $this->printButton;
$dataOrderDetail = $this->dataOrderDetail;
$this->titleHelper($title);

?>
    <div class="row-fluid">
        <div class="span3">
            <?php $this->detailHelper($dataOrder); ?>
        </div>
        <div class="span9">
            <?php $this->tableHelper($dataOrderDetail); ?>
        </div>
    </div>
<?php
//render detail of order


//render table detail


$this->printHelper($button);
