<?php
$translator = \Velacolib\Utility\Utility::translate();
$config = Velacolib\Utility\Utility::getConfig();

?>
<header>
    <div class="logo-header">
        <a href="<?php //echo $this->url('admin') ?>"> <img src="<?php echo '/img/upload/config/logo-inner.png'; ?>" /> </a>
    </div>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">

                <a class="toggle-nav btn pull-left" style="margin-left: 10px" href="#">
                    <i class="icon-reorder"></i>
                </a>

                <ul style="margin-left: 5px" class="nav pull-right">
                    <li class="dropdown light only-icon">

                        <ul class="dropdown-menu color-settings">
                            <li class="color-settings-body-color">
                                <div class="color-title">Body color</div>
                                <a data-change-to="css/backend/light-theme.css" href="#">
                                    Light
                                    <small>(default)</small>
                                </a>
                                <a data-change-to="css/backend/dark-theme.css" href="#">
                                    Dark
                                </a>
                                <a data-change-to="css/backend/dark-blue-theme.css" href="#">
                                    Dark blue
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li class="color-settings-contrast-color">
                                <div class="color-title">Contrast color</div>
                                <a href="#" data-change-to="contrast-red"><i class="icon-adjust text-red"></i>
                                    Red
                                    <small>(default)</small>
                                </a>
                                <a href="#" data-change-to="contrast-blue"><i class="icon-adjust text-blue"></i>
                                    Blue
                                </a>
                                <a href="#" data-change-to="contrast-orange"><i class="icon-adjust text-orange"></i>
                                    Orange
                                </a>
                                <a href="#" data-change-to="contrast-purple"><i class="icon-adjust text-purple"></i>
                                    Purple
                                </a>
                                <a href="#" data-change-to="contrast-green"><i class="icon-adjust text-green"></i>
                                    Green
                                </a>
                                <a href="#" data-change-to="contrast-muted"><i class="icon-adjust text-muted"></i>
                                    Muted
                                </a>
                                <a href="#" data-change-to="contrast-fb"><i class="icon-adjust text-fb"></i>
                                    Facebook
                                </a>
                                <a href="#" data-change-to="contrast-dark"><i class="icon-adjust text-dark"></i>
                                    Dark
                                </a>
                                <a href="#" data-change-to="contrast-pink"><i class="icon-adjust text-pink"></i>
                                    Pink
                                </a>
                                <a href="#" data-change-to="contrast-grass-green"><i class="icon-adjust text-grass-green"></i>
                                    Grass green
                                </a>
                                <a href="#" data-change-to="contrast-sea-blue"><i class="icon-adjust text-sea-blue"></i>
                                    Sea blue
                                </a>
                                <a href="#" data-change-to="contrast-banana"><i class="icon-adjust text-banana"></i>
                                    Banana
                                </a>
                                <a href="#" data-change-to="contrast-dark-orange"><i class="icon-adjust text-dark-orange"></i>
                                    Dark orange
                                </a>
                                <a href="#" data-change-to="contrast-brown"><i class="icon-adjust text-brown"></i>
                                    Brown
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown medium only-icon widget">

                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">
                                    <div class="widget-body">
                                        <div class="pull-left icon">
                                            <i class="icon-user text-success"></i>
                                        </div>
                                        <div class="pull-left text">
                                            John Doe signed up
                                            <small class="muted">just now</small>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div class="widget-body">
                                        <div class="pull-left icon">
                                            <i class="icon-inbox text-error"></i>
                                        </div>
                                        <div class="pull-left text">
                                            New Order #002
                                            <small class="muted">3 minutes ago</small>
                                        </div>
                                    </div>
                                </a>
                            </li>

                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div class="widget-body">
                                        <div class="pull-left icon">
                                            <i class="icon-user text-success"></i>
                                        </div>
                                        <div class="pull-left text">
                                            Jane Doe signed up
                                            <small class="muted">last week</small>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">
                                    <div class="widget-body">
                                        <div class="pull-left icon">
                                            <i class="icon-inbox text-error"></i>
                                        </div>
                                        <div class="pull-left text">
                                            New Order #001
                                            <small class="muted">1 year ago</small>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="widget-footer">
                                <a href="#">All notifications</a>
                            </li>
                        </ul>
                    </li>
                    <?php
                    $user = \Velacolib\Utility\Utility::checkLogin();
                    if($user){
//                        echo '<pre>';
//                        print_r($user);
//                        echo '</pre>';
                        ?>
                        <li class="dropdown dark user-menu ">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <?php if(isset($user->image)){ ?>
                                    <img alt="<?php echo $user->userName; ?>" height="23" src="/assets/images/avatar.jpg" width="23">
                                <?php } ?>

                                <span class="user-name hidden-phone"><?php echo $user->userName ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                            <li>
                                <a href="/admin/login/logout">
                                    <i class="icon-signout"></i>
                                    <?php echo $translator->translate('Sign out') ?>
                                </a>
                            </li>
                            </ul>

                    </li>
                    <?php } ?>
                </ul>
                <a class=" btn btn-success pull-right" href="/frontend/order/add">
                    <i class="icon-Plus"></i> <?php echo $translator->translate('Add new order') ?>
                </a>

            </div>
        </div>
    </div>
</header>
<div id='wrapper'>
    <div id='main-nav-bg'></div>
    <nav class='' id='main-nav'>
        <div class='navigation'>
            <div class='search'>
                <form accept-charset="UTF-8" action="search_results.html" method="get"/>
                <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;"/></div>
                <div class='search-wrapper'>
                    <input autocomplete="off" class="search-query" id="q" name="q" placeholder="Search..." type="text" value=""/>
                    <button class="btn btn-link icon-search" name="button" type="submit"></button>
                </div>
                </form>
            </div>