<!-- / jquery -->
<script src='/js/backend/jquery/jquery.min.js' type='text/javascript'></script>
<!-- / jquery mobile events (for touch and slide) -->
<script src='/js/backend/plugins/mobile_events/jquery.mobile-events.min.js' type='text/javascript'></script>
<!-- / jquery migrate (for compatibility with new jquery) -->
<script src='/js/backend/jquery/jquery-migrate.min.js' type='text/javascript'></script>
<!-- / jquery ui -->
<script src='/js/backend/jquery_ui/jquery-ui.min.js' type='text/javascript'></script>
<!-- / bootstrap -->
<script src='/js/backend/bootstrap/bootstrap.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/flot/excanvas.js' type='text/javascript'></script>
<!-- / sparklines -->
<script src='/js/backend/plugins/sparklines/jquery.sparkline.min.js' type='text/javascript'></script>
<!-- / flot charts -->
<script src='/js/backend/plugins/flot/flot.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/flot/flot.resize.js' type='text/javascript'></script>
<script src='/js/backend/plugins/flot/flot.pie.js' type='text/javascript'></script>
<!-- / bootstrap switch -->
<script src='/js/backend/plugins/bootstrap_switch/bootstrapSwitch.min.js' type='text/javascript'></script>
<!-- / fullcalendar -->
<script src='/js/backend/plugins/fullcalendar/fullcalendar.min.js' type='text/javascript'></script>
<!-- / datatables -->
<!--<script src='/js/backend/plugins/datatables/jquery.dataTables.min.js' type='text/javascript'></script>-->
<!--<script src='/js/backend/plugins/datatables/jquery.dataTables.columnFilter.js' type='text/javascript'></script>-->

<script src='/js/jquery.dataTables.js' type='text/javascript'></script>
<script src='/js/datatables-bootstrap.js' type='text/javascript'></script>

<!-- / wysihtml5 -->
<script src='/js/backend/plugins/common/wysihtml5.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/common/bootstrap-wysihtml5.js' type='text/javascript'></script>
<!-- / select2 -->
<script src='/js/backend/plugins/select2/select2.js' type='text/javascript'></script>
<!-- / color picker -->
<script src='/js/backend/plugins/bootstrap_colorpicker/bootstrap-colorpicker.min.js' type='text/javascript'></script>
<!-- / mention -->
<script src='/js/backend/plugins/mention/mention.min.js' type='text/javascript'></script>
<!-- / input mask -->
<script src='/js/backend/plugins/input_mask/bootstrap-inputmask.min.js' type='text/javascript'></script>
<!-- / fileinput -->
<script src='/js/backend/plugins/fileinput/bootstrap-fileinput.js' type='text/javascript'></script>
<!-- / modernizr -->
<script src='/js/backend/plugins/modernizr/modernizr.min.js' type='text/javascript'></script>
<!-- / retina -->
<script src='/js/backend/plugins/retina/retina.js' type='text/javascript'></script>
<!-- / fileupload -->
<script src='/js/backend/plugins/fileupload/tmpl.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/load-image.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/canvas-to-blob.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/jquery.iframe-transport.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/jquery.fileupload.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/jquery.fileupload-fp.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/jquery.fileupload-ui.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/fileupload/jquery.fileupload-init.js' type='text/javascript'></script>
<!-- / timeago -->
<script src='/js/backend/plugins/timeago/jquery.timeago.js' type='text/javascript'></script>
<!-- / slimscroll -->
<script src='/js/backend/plugins/slimscroll/jquery.slimscroll.min.js' type='text/javascript'></script>
<!-- / autosize (for textareas) -->
<script src='/js/backend/plugins/autosize/jquery.autosize-min.js' type='text/javascript'></script>
<!-- / charCount -->
<script src='/js/backend/plugins/charCount/charCount.js' type='text/javascript'></script>
<!-- / validate -->
<script src='/js/backend/plugins/validate/jquery.validate.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/validate/additional-methods.js' type='text/javascript'></script>
<!-- / naked password -->
<script src='/js/backend/plugins/naked_password/naked_password-0.2.4.min.js' type='text/javascript'></script>
<!-- / nestable -->
<script src='/js/backend/plugins/nestable/jquery.nestable.js' type='text/javascript'></script>
<!-- / tabdrop -->
<script src='/js/backend/plugins/tabdrop/bootstrap-tabdrop.js' type='text/javascript'></script>
<!-- / jgrowl -->
<script src='/js/backend/plugins/jgrowl/jquery.jgrowl.min.js' type='text/javascript'></script>
<!-- / bootbox -->
<script src='/js/backend/plugins/bootbox/bootbox.min.js' type='text/javascript'></script>
<!-- / inplace editing -->
<script src='/js/backend/plugins/xeditable/bootstrap-editable.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/xeditable/wysihtml5.js' type='text/javascript'></script>
<!-- / ckeditor -->
<script src='/js/backend/plugins/ckeditor/ckeditor.js' type='text/javascript'></script>
<!-- / filetrees -->
<script src='/js/backend/plugins/dynatree/jquery.dynatree.min.js' type='text/javascript'></script>
<!-- / datetime picker -->
<script src='/js/backend/plugins/bootstrap_datetimepicker/bootstrap-datetimepicker.js' type='text/javascript'></script>
<!-- / daterange picker -->
<script src='/js/backend/plugins/bootstrap_daterangepicker/moment.min.js' type='text/javascript'></script>
<script src='/js/backend/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.js' type='text/javascript'></script>
<!-- / max length -->
<script src='/js/backend/plugins/bootstrap_maxlength/bootstrap-maxlength.min.js' type='text/javascript'></script>
<!-- / dropdown hover -->
<script src='/js/backend/plugins/bootstrap_hover_dropdown/twitter-bootstrap-hover-dropdown.min.js' type='text/javascript'></script>
<!-- / slider nav (address book) -->
<script src='/js/backend/plugins/slider_nav/slidernav-min.js' type='text/javascript'></script>
<!-- /  -->

<script src='/js/backend/plugins/fuelux/wizard.js' type='text/javascript'></script>
<script src='/js/price_format.js' type='text/javascript'></script>
<script src='/js/bootstrap-tooltip.js' type='text/javascript'></script>

<!-- /  theme -->
<script src='/js/backend/nav.js' type='text/javascript'></script>
<script src='/js/backend/tables.js' type='text/javascript'></script>
<script src='/js/backend/theme.js' type='text/javascript'></script>
<!-- / demo -->
<script src='/js/backend/demo/jquery.mockjax.js' type='text/javascript'></script>
<script src='/js/backend/demo/inplace_editing.js' type='text/javascript'></script>
<script src='/js/backend/demo/charts.js' type='text/javascript'></script>
<script src='/js/jwerty.js' type='text/javascript'></script>
<script src='/js/jqueryte/jquery-te-1.4.0.min.js' type='text/javascript'></script>
<script src='/js/backend/demo/demo.js' type='text/javascript'></script>
<script src='/js/UnitCalc.js' type='text/javascript'></script>
<script src='/js/backend/backend.js' type='text/javascript'></script>
<script src='/js/backend/hotkey.js' type='text/javascript'></script>



<script type="text/javascript" src="https://www.google.com/jsapi"></script>
