<link href='/css/backend/bootstrap/bootstrap.css' media='all' rel='stylesheet' type='text/css' />
<link href='/css/backend/bootstrap/bootstrap-responsive.css' media='all' rel='stylesheet' type='text/css' />
<!-- / jquery ui -->
<link href='/css/backend/jquery_ui/jquery-ui-1.10.0.custom.css' media='all' rel='stylesheet' type='text/css' />
<link href='/css/backend/jquery_ui/jquery.ui.1.10.0.ie.css' media='all' rel='stylesheet' type='text/css' />
<!-- / switch buttons -->
<link href='/css/backend/plugins/bootstrap_switch/bootstrap-switch.css' media='all' rel='stylesheet' type='text/css' />
<!-- / xeditable -->
<link href='/css/backend/plugins/xeditable/bootstrap-editable.css' media='all' rel='stylesheet' type='text/css' />
<link href='/css/backend/plugins/common/bootstrap-wysihtml5.css' media='all' rel='stylesheet' type='text/css' />
<!-- / wysihtml5 (wysywig) -->
<link href='/css/backend/plugins/common/bootstrap-wysihtml5.css' media='all' rel='stylesheet' type='text/css' />
<!-- / jquery file upload -->
<link href='/css/backend/plugins/jquery_fileupload/jquery.fileupload-ui.css' media='all' rel='stylesheet' type='text/css' />
<!-- / full calendar -->
<link href='/css/backend/plugins/fullcalendar/fullcalendar.css' media='all' rel='stylesheet' type='text/css' />
<!-- / select2 -->
<link href='/css/backend/plugins/select2/select2.css' media='all' rel='stylesheet' type='text/css' />
<!-- / mention -->
<link href='/css/backend/plugins/mention/mention.css' media='all' rel='stylesheet' type='text/css' />
<!-- / tabdrop (responsive tabs) -->
<link href='/css/backend/plugins/tabdrop/tabdrop.css' media='all' rel='stylesheet' type='text/css' />
<!-- / jgrowl notifications -->
<link href='/css/backend/plugins/jgrowl/jquery.jgrowl.min.css' media='all' rel='stylesheet' type='text/css' />
<!-- / datatables -->
<link href='/css/backend/plugins/datatables/bootstrap-datatable.css' media='all' rel='stylesheet' type='text/css' />
<!-- / dynatrees (file trees) -->
<link href='/css/backend/plugins/dynatree/ui.dynatree.css' media='all' rel='stylesheet' type='text/css' />
<!-- / color picker -->
<link href='/css/backend/plugins/bootstrap_colorpicker/bootstrap-colorpicker.css' media='all' rel='stylesheet' type='text/css' />
<!-- / datetime picker -->
<link href='/css/backend/plugins/bootstrap_datetimepicker/bootstrap-datetimepicker.min.css' media='all' rel='stylesheet' type='text/css' />
<!-- / daterange picker) -->
<link href='/css/backend/plugins/bootstrap_daterangepicker/bootstrap-daterangepicker.css' media='all' rel='stylesheet' type='text/css' />
<!-- / flags (country flags) -->
<link href='/css/backend/plugins/flags/flags.css' media='all' rel='stylesheet' type='text/css' />
<!-- / slider nav (address book) -->
<link href='/css/backend/plugins/slider_nav/slidernav.css' media='all' rel='stylesheet' type='text/css' />
<!-- /  (wizard) -->
<link href='/css/backend/plugins/fuelux/wizard.css' media='all' rel='stylesheet' type='text/css' />
<!-- /  theme -->
<link href='/css/backend/light-theme.css' id='color-settings-body-color' media='all' rel='stylesheet' type='text/css' />
<!-- / demo -->
<link href='/css/backend/demo.css' media='all' rel='stylesheet' type='text/css' />
<link href='/css/style.css' media='all' rel='stylesheet' type='text/css' />
<link href='/js/jqueryte/jquery-te-1.4.0.css' media='all' rel='stylesheet' type='text/css' />