<div class="page-header">
    <h1 class="pull-left">
        <i class="icon-table"></i>
        <span><?php echo $this->title; ?></span>
    </h1>
    <div class="pull-right">
        <ul class="breadcrumb">
            <li>
                <a href=""><i class="icon-bar-chart"></i>
                </a>
            </li>
            <li class="separator">
                <i class="icon-angle-right"></i>
            </li>
            <li class="active"><?php echo $this->title; ?></li>
        </ul>
    </div>
</div>
<?php $this->flashHelper(); ?>