<div class="page-header">
    <h1 class="pull-left">
        <i class="icon-table"></i>
        <span><?php echo $title['title']; ?></span>
    </h1>
    <div class="pull-right">

        <ul class="breadcrumb">
            <li>
                <a href=""><i class="icon-bar-chart"></i>
                </a>
            </li>

            <li class="separator">
                <i class="icon-angle-right"></i>
            </li>
            <li class="active"><?php echo $title['title']; ?></li>
            <?php if(isset($title['link']) && $title['link'] != ''){ ?>
                <li class="separator">
                    <i class="icon-angle-right"></i>
                </li>
                <li>
                    <a href="<?php echo $title['link']; ?>" class="btn btn-primary">Add</a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<?php $this->flashHelper(); ?>