<?php
$translator = \Velacolib\Utility\Utility::translate();
$config = Velacolib\Utility\Utility::getConfig();


?>
<!DOCTYPE html>
<html lang="vi-VN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title><?php echo $config['sitename']; ?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'/>

    <!--[if lt IE 9]>
    <script src='js/backend/html5shiv.js' type='text/javascript'></script>

    <![endif]-->
    <!-- hepler style here -->
    <?php $this->styleHelper(); ?>
    <!--end helper style -->

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <script src="https://apis.google.com/js/client:platform.js" async defer></script>
    <script>

        function signinCallback(authResult) {
            if (authResult['status']['signed_in']) {
                // Update the app to reflect a signed in user
                // Hide the sign-in button now that the user is authorized, for example:
                document.getElementById('signinButton').setAttribute('style', 'display: none');
                console.log(authResult);
                $.ajax({
                    type: 'POST',
                    url: 'http://'+window.location.host+'/frontend/login/google?token='+ authResult['access_token']+'&code='+authResult['code']+'&state='+authResult['state'] ,
                    contentType: 'application/octet-stream; charset=utf-8',
                    success: function(result) {
                        // Handle or verify the server response if necessary.

                        // Prints the list of people that the user has allowed the app to know
                        // to the console.
                        console.log(result);
                        if (result['profile'] && result['people']){
                            $('#results').html('Hello ' + result['profile']['displayName'] + '. You successfully made a server side call to people.get and people.list');
                        } else {
                            $('#results').html('Failed to make a server-side call. Check your configuration and console.');
                        }
                    },
                    processData: false,
                    data: authResult['code']
                });
            } else {
                // Update the app to reflect a signed out user
                // Possible error values:
                //   "user_signed_out" - User is signed-out
                //   "access_denied" - User denied access to your app
                //   "immediate_failed" - Could not automatically log in the user
                console.log('Sign-in state: ' + authResult['error']);
            }
        }
    </script>

    <link href='/css/login.css' media='all' rel='stylesheet' type='text/css' />
    <style>
        /* start css login layout*/
        .contrast-red{
            background: url("../img/kaffa-bg-2.jpg") no-repeat !important;
            background-size: cover !important;;

        }
        #wrap-login{
            padding: 20px;
        }
        #wrap-login .login-form{
            background: #ffffff;
            padding: 10px 20px 10px 20px;
            border-radius: 10px;
        }
        .cms-title-login{
            border-bottom: 2px solid #d2d2d2;
            font-weight: bold;
            color: #222222;
        }
        .cms-title-login span{
            color: #603913;
            font-family: "DejaVu Sans Mono", monospace;
        }
        .img-owl{
            text-align: center;
        }
        #powerby {
            text-align: right;
            font-weight: bold;
        }
        #powerby span{
            font-size: 12px;
            color: #000000;

        }
        .login-form form{
            margin-bottom: 0px !important;
        }
        .login-form label{
            font-weight: bold;
            color: #313131;
        }
        .input-radius{
            border-radius: 5px;
        }
        .btn-signin , .btn-signin:hover{
            background: #666666;
            border-radius: 5px !important;
            color: #ffffff;
        }
        @media screen and (min-width: 980px){
            #wrap-login{
                margin-top: 50px;
                min-height: inherit;
            }

        }

        @media (max-width: 979px) {
            #wrap-login{
                margin-top: 90px !important;
            }
            #wrap-login .login-form{
                width: 100%;
            }
        }
    </style>
</head>
<body class='contrast-red  contrast-background'>
<div id='wrapper'>
    <?php echo $this->content; ?>
</div>


<!--- script helper -->
<?php $this->scriptHelper(); ?>
<!-- end script helper -->
</body>
</html>