<?php
$title = array();
$title['title'] = $this->title;
$title['link'] =   $this->url('admin/child', array('controller'=>'tracking-tore','action' => 'add'));
$this->titleHelper($title);
$data = $this->data;
$translator = \Velacolib\Utility\Utility::translate();
?>
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header blue-background">
            <div class="title">
                <div class="icon-edit"></div>
                <?php echo $this->title; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <form accept-charset="UTF-8" action="<?php
            $url = $this->url('admin/child',array('controller'=>'users','action'=>'add'));
            if($data){
                $url = $this->url('admin/child',array('controller'=>'users','action'=>'add','id'=>$data->getId()));
            }
            echo $url; ?>" class="form form-horizontal" method="post"
                  style="margin-bottom: 0;">
                <input type="hidden" name="id" value="<?php if($data){ echo $data->getId();} ?>">
                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('Users name') ?></label>
                    <div class="controls">
                        <input id="" placeholder="User Name" name="userName" type="text" value="<?php if($data){echo $data->getUserName();} ?>">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('Full name') ?></label>
                    <div class="controls">
                        <input id="" placeholder="Full Name" name="fullName" type="text" value="<?php if($data){echo $data->getFullName();} ?>">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('password'); ?></label>
                    <div class="controls">
                        <input id="" placeholder="Password" name="password" type="password" value="<?php if($data){echo '';} ?>">
                    </div>
                </div>

<!--                <div class="control-group">-->
<!--                    <label class="control-label" for="inputTextArea1">Description</label>-->
<!---->
<!--                    <div class="controls">-->
<!--                        <textarea id="" name="desc" placeholder="Textarea" rows="3">--><?php //if($data){echo $data->getdescription();} ?><!--</textarea>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="control-group">-->
<!--                    <label class="control-label">Category</label>-->
<!--                    <div class="controls">-->
<!--                        --><?php
//                        $categories = Velacolib\Utility\Utility::getCategories();
//                        //                        print_r($categories);
//                        ?>
<!--                        <select name="cat_id" id="inputSelect">-->
<!--                            --><?php
//                            foreach($categories as $cat){
//                                $selected = '';
//                                if($data){
//                                    $catID = $data->getCatId();
//                                    if($catID == $cat->getId())
//                                        $selected = 'selected';
//
//                                }
//
//                                echo ' <option value="'.$cat->getId().'"'.$selected.' >'.$cat->getName().'</option>';
//                            }
//                            ?>
<!--                        </select>-->
<!--                    </div>-->
<!--                </div>-->


                <div class="form-actions">
                    <button class="btn btn-primary" type="submit">
                        <i class="icon-save"></i>
                       <?php echo $translator->translate('Save'); ?>
                    </button>
                    <button class="btn" type="submit">
                        <?php echo $translator->translate('Cancel'); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>