<?php
$title = array();
$title['title'] = $this->title;
$title['link'] =   $this->url('admin/child', array('controller'=>'order','action' => 'add'));
$this->titleHelper($title);
$partialData = array(
    'ajaxUrl' => $this->url('admin/child', array('controller'=>'users','action' => 'ajax-list')),
    'actions' => array(
        'edit' => array('action' => 'edit', 'label' => 'Edit'),
        'delete' => array('action' => 'delete', 'label' => 'Delete')
    ),
    'columns' => array(
        0 => array('field' => 'id',   'searchable' => false,  'primaryKey' => true),
        1 => array('field' => 'userName',    'label' => 'User name',    'searchable' => true,   'sortable' => true),
        2 => array('field' => 'fullName',    'label' => 'Full name',    'searchable' => true,   'sortable' => true),
        3 => array('field' => 'type',    'label' => 'Type',    'searchable' => true,   'sortable' => true),
        4 => array('field' => 'apiKey',    'label' => 'Api key',    'searchable' => true,   'sortable' => true),
        5 => array('field' => 'action',    'label' => 'Action',    'searchable' => true, 'action'=>true ,  'sortable' => false),
    )
);

echo $this->partial('partial/listing.phtml',$partialData);