<?php
$title = array();
$title['title'] = $this->title;
$title['link'] =   $this->url('admin/child', array('controller'=>'surtax','action' => 'add'));
$this->titleHelper($title);
$data = $this->data;
$translator = \Velacolib\Utility\Utility::translate();
?>
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header blue-background">
            <div class="title">
                <div class="icon-edit"></div>
                <?php echo $this->title; ?>
            </div>
            <div class="actions">
                <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>
                </a>
                <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
                </a>
            </div>
        </div>
        <div class="box-content">
            <form accept-charset="UTF-8" action="<?php
            $url = $this->url('admin/child',array('controller'=>'surtax','action'=>'add'));
            if($data){
                $url = $this->url('admin/child',array('controller'=>'surtax','action'=>'add','id'=>$data->getId()));
            }
            echo $url; ?>" class="form form-horizontal" method="post"
                  style="margin-bottom: 0;">
                <input type="hidden" name="id" value="<?php if($data){ echo $data->getId();} ?>">
                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('Name'); ?></label>
                    <div class="controls">
                        <input id="" placeholder="Name" name="name" type="text" value="<?php if($data){echo $data->getName();} ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('Value'); ?></label>
                    <div class="controls">
                        <input id="" placeholder="Value" name="value" type="text" value="<?php if($data){echo $data->getValue();} ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputText1"><?php echo $translator->translate('Type'); ?></label>
                    <div class="controls">
                        <select name="type">
                            <option  value="percent" <?php if(($data) && $data->getType() == 'percent'){echo 'selected'; } ?>>
                                <?php echo $translator->translate('Percent'); ?>
                            </option>
                            <option value="cash" <?php if(($data) && $data->getType() == 'cash'){echo 'selected'; } ?> >
                                <?php echo $translator->translate('Cash'); ?>
                            </option>
                        </select>

                    </div>
                </div>
                <div class="form-actions">
                    <button class="btn btn-primary" type="submit">
                        <i class="icon-save"></i>
                        <?php echo $translator->translate('Save'); ?>
                    </button>
                    <button class="btn" type="submit"><?php echo $translator->translate('Cancel'); ?></button>
                </div>
            </form>
        </div>
    </div>
</div>