<?php
$data = $this->data;
$title = array();
$title['title'] = $this->title;
$this->titleHelper($title);
$partialData = array(
    'ajaxUrl' => $this->url('admin/child', array('controller'=>'menustoremain','action' => 'detailAjax','id'=>$id)),
    'actions' => array(
        'edit' => array('action' => 'edit', 'label' => 'Edit'),
        'delete' => array('action' => 'delete', 'label' => 'Delete')
    ),
    'columns' => array(
        0 => array('field' => 'id',                                    'searchable' => false,  'primaryKey' => false),
        1 => array('field' => 'menuStoreId',    'label' => 'Menu store',    'searchable' => true,   'sortable' => true),
        2 => array('field' => 'action',    'label' => 'Action',    'searchable' => true,   'sortable' => true),
        3 => array('field' => 'quantity',    'label' => 'Quantity out',    'searchable' => true,   'sortable' => true),
        4 => array('field' => 'unit',    'label' => 'Unit',    'searchable' => true,   'sortable' => true),
        5 => array('field' => 'date',    'label' => 'Date',    'searchable' => true,   'sortable' => true),
        6 => array('field' => 'cost',    'label' => 'Cost',    'searchable' => true,   'sortable' => true),
        7 => array('field' => 'note',    'label' => 'Note',    'searchable' => true,   'sortable' => true),
        8 => array('field' => 'supplier',    'label' => 'Supplier',    'searchable' => true, 'sortable' => false),
    )
);

echo $this->partial('partial/listing.phtml', $partialData);