<?php
$title = array();
$title['title'] = $this->title;
$title['link'] =   $this->url('admin/child', array('controller'=>'menustoremain','action' => 'add'));
$this->titleHelper($title);
$partialData = array(
    'ajaxUrl' => $this->url('admin/child', array('controller'=>'menustoremain','action' => 'inout-ajax')),
    'actions' => array(
        'edit' => array('action' => 'edit', 'label' => 'Edit'),
        'delete' => array('action' => 'delete', 'label' => 'Delete')
    ),
    'columns' => array(
        0 => array('field' => 'id', 'searchable' => false,  'primaryKey' => true),
        1 => array('field' => 'menuStoreId',    'label' => 'Store name',    'searchable' => true,   'sortable' => true),
        2 => array('field' => 'quantity',    'label' => 'Quantity',    'searchable' => true,   'sortable' => true),
        3 => array('field' => 'unit',    'label' => 'Unit',    'searchable' => true,   'sortable' => true),
        4 => array('field' => 'cost',    'label' => 'Cost',    'searchable' => true,   'sortable' => true),
        5 => array('field' => 'action',    'label' => 'Action',    'searchable' => true,   'sortable' => true),
        6 => array('field' => 'note',    'label' => 'Note',    'searchable' => true,   'sortable' => true),
        7 => array('field' => 'actions',    'label' => 'Action',    'searchable' => true, 'action'=>true ,  'sortable' => false),
    )
);

echo $this->partial('partial/listing.phtml',$partialData);