<?php

$title = $this->title;
$link = $this->link;
$buttonLogin = $this->buttonLogin;
//$this->titleHelper($title);
$config = \Velacolib\Utility\Utility::getConfig();

?>
<!--<div class="span12 box" style="margin: 0px !important;">-->
<!--    <div class="box-header blue-background">-->
<!--        <div class="title">--><?php //echo $title; ?><!--</div>-->
<!--        <div class="actions">-->
<!--            <a href="#" class="btn box-remove btn-mini btn-link"><i class="icon-remove"></i>-->
<!--            </a>-->
<!--            <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>-->
<!--            </a>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="box-content">-->
<!--        <form method="post" action="--><?php //echo $link; ?><!--" class="form form-horizontal validate-form" style="margin-bottom: 0;" novalidate="novalidate">-->
<!--            <div class="control-group">-->
<!--                <label class="control-label" for="validation_name">--><?php //echo $this->userNameText ?><!--</label>-->
<!--                <div class="controls">-->
<!--                    <input data-rule-minlength="2" data-rule-required="true" id="" name="userName" placeholder="User Name" type="text">-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="control-group">-->
<!--                <label class="control-label" for="validation_email">--><?php //echo $this->passwordText ?><!--</label>-->
<!--                <div class="controls">-->
<!--                    <input  data-rule-required="true" id="" name="password" placeholder="Password" type="password">-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="form-actions" style="margin-bottom:0">-->
<!--                <button class="btn btn-primary" type="submit">-->
<!--                    <i class="icon-save"></i>-->
<!--                    --><?php //echo $buttonLogin; ?>
<!--                </button>-->
<!--            </div>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->

<div class='application'>
    <div class='application-content'>
        <a href="#">
            <div class='icon-heart'></div>
            <span><?php echo $config['sitename'] ?></span>
        </a>
    </div>
</div>
<div class='controls'>
    <div class='caret'></div>
    <div class='form-wrapper'>
        <h1 class='text-center'>Sign in</h1>

        <form accept-charset="UTF-8" action="<?php echo $link; ?>" method="post"/>
        <div style="margin:0;padding:0;display:inline"></div>
        <div class='row-fluid'>
            <div class='span12 icon-over-input'>
                <input class="span12" data-rule-minlength="2" data-rule-required="true" id="" name="userName"
                       placeholder="User Name" type="text">
                <i class='icon-user muted'></i>
            </div>
        </div>
        <div class='row-fluid'>
            <div class='span12 icon-over-input'>
                <input class="span12" data-rule-required="true" id="" name="password" placeholder="Password"
                       type="password">
                <i class='icon-lock muted'></i>
            </div>
        </div>

        <button class="btn btn-block" type="submit">Sign in</button>
        </form>

        <div class='text-center'>
            <hr class='hr-normal'/>

        </div>
<!--         <span id="signinButton">-->
<!--          <span-->
<!--              class="g-signin"-->
<!--              data-callback="signinCallback"-->
<!--              data-clientid="927311531718-rps1cvcjnd2m6g5m3133gu0m8t7pq1m1.apps.googleusercontent.com"-->
<!--              data-cookiepolicy="single_host_origin"-->
<!--              data-requestvisibleactions="http://schema.org/AddAction"-->
<!--              data-scope="https://www.googleapis.com/auth/plus.login">-->
<!--          </span>-->
<!--        </span>-->
    </div>
</div>
<div class='login-action text-center'>
    <a href=""><i class='icon-user'></i>
        <?php //echo $config['sitename'] ?>
    </a>
</div>